apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: notion-to-calendar
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        namespace: music-projects-local
