---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notion-to-calendar-secrets
spec:
  encryptedData:
    NOTION_CALENDAR_NAME: AgA235cb/MZHou+OSxuBvm3iCmNZsnrRmX5u+PksiUuoeECI9EhHNnDTl4Fm8k+iNuGHojq9bkEe/kUCsM8UNisYF7LJxGnMQii48IXdXO9JYDToMvIGkJIkeffNsIrnWFANYKHyA2crA2BrZz0b+X2MfgSPJWY04fesLOYqRx8QfofYsilOyU6aTvfdHXiVGNbs96N917pXhGSX6Td6heaUyqOrfbnUHuBnEdJQTV00L3t4x30DSD6N+3nd//e/mRM1ctBP7owZ0himLM0+GuZf7Is+PQC/uWmtGR+zey40tnDRWSDICMlskW0gtPXlXjqQKtiSRgwh0CtpysEsgwfeG2Y2B49q6VX0ln3hvlAeW2WGSQKI4UrFOgHWjf9tSykfWl8q+gNAcd5jJ8o5mfk7PV0i/CWs1aqoZibSgUExMoX4VcLp0dkZdlXBIfPFC5E/NahD2NEUvazx9E9hbpt6nnAizFnHBOM9DINFgjiU2zRfllbQOyIZq6UKbBvjSm1kKT6woDrXwaA60988+TwWoGwGgHteivXAJr1a9nK5RbZqfCN/mH1wNDN6UdwTvF3l3hnYUUM+NLFNRuRIiHilampyVOuOoGeRTh4X84TXBL79OUtGnRJrOtYwQ1SidGngAykAEP65IMMndcfwmo4QsJADL/zJ5SpLTzrY6fehOOdrev4WI4Ayyyy1VgD5D+IyWIxVoEAiVf8rlCOvFWzlP9oCQiRiwiSewwzKEvdhwtsUkepPWK4aahzvGiVSYaXWDmfyXE6zM2ayHEPTAzH9JoKzVlY78FnLlOqktOWr3gMAeT8mvSed+mQ=
    NOTION_TOKEN: AgBjr6HnfYUVMx/a04EZJCr+krzte8Fsl/38t97zcJ/yIWF5xVJLYR1Ce/inHSrw4K0PRARk+akH8B9JgJXMoCVsdgLFhKO5NFHsEYMSfDjcyFh978PXST6fFc6R6767yaFirXnKNJYucXEICWmUc4P8E50TDQfqp17JOJ4xL9596+H5rLU4HCdzMH57WmbtBVDJuIQ/hc3tNxGeC+9jmgiCy3Q5kspIEtJN//yXy8+5wJKrcGsCtgCZxTUQmRM7wPdRhIYiUekQJ31u2xn9XPYUjWiYqAvO+VW0uXj5dtwBpjFWLfBODjzB/hHO4sLaIUXw1mxKETi0gT0b3UqrCLLxjrZeTgOenusDhBxEHt0dTR/4zhZyK+QMG632GgfZNHThvpFU/sOOEKLechZXz3MPzHF+sDjuelTrOv/MaO4dIuRR/1fORjMJzTL/4BmyWh7JMvCKmoeSwNByZF629Ye3bUxyYtYvxFbjqV/JBL98UbOrur2t5wwnfPR6TnGr62V2doDcMA6j2rIWIP1djr83RftfohEuLtomtUhT0X06d7s9GASuys2zl/mBLB6wWUoU1M8lWIaZyi4cw33QzsLAr0KgtADvu6a73eITtitH435XqdtRTLTFtjEedgQSb/kdqRdHXAnW8aQeNT9WhRq/fyhBY7slpZARIMAxzp5Iufvx+X+Xnfjp97iH+lXzeOprRVYgd3MZ8T+ra84rBoAaHPA+aEUi9NOeopTufL/vt4897aRPGss5G0PuwtiqkcG39g==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notion-to-calendar
      name: notion-to-calendar-secrets
      namespace: music-projects
    type: Opaque
