---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notion-to-calendar-secrets
  namespace: default
spec:
  encryptedData:
    NOTION_CALENDAR_NAME: AgBQhcZHi2c8OzCmdgT9hY+S2n24N7p0d8ONjEbYscl6/iiyYhuSYM5MBmd5dgaGAIWZoiqPoDmfqDgIfsMmbJZ8OzDK3w1iQwPYRGGS1yFytQ0Ohih1e3B9XDoFR6vKgPVESy60Wi2/2z7DdhpFkHdMaHLRMGmSv7VOsGwLV91faw6zdSSPfxk3/43ELu0xxEibIe4iQqcquvCMLFgpdsNzMWQrq8pBWEsisfyDgeJbr8SbSULDQpwRmqp3L6BjBJ+vucm1A41XSZGB+phyrEcQ80gHTqlP3F+KaNKusJA+VhpVZdP81o1na8tBeH7DTL1kLDsAaA8KMl+30vCNn5dQMspRRqN7DrXHViK54QHfbW+20YZWjmb8/aOmugttAj1e4ePidrNLxetpc0IMbxZmz9JeZ+/hwJVhfCpinziIGa7tF9IQO2VModT98ihB8ZIfSldAzB5MIXTOQAn46bwT2xd3/mRmUbLiix/9gen0fxNSObUZLplM85GXr6Js917RfDT4yEVkPQZ6fNDK2zrapp99lTGoR00i8b9ZWdxhMXE7MqbGd/soXqo4Q03L+c8SYCNeX2ZTyECdujkRfa/C+59xHUEfvsR+Kdi8O1CKkYSzLxmGCG5AA5aYYnVGK6gyKB0K8ZqvKwKB7sqRozkAyRdzn66vG3yALlecEfxKP0hQ5tIIhklqjmZkoPaGzw0RSFGZ9xKF3chEeyb2ZkBPEY60REy9cg6mWeKCcWyQFR8EPezYF+YWW9OJivoOso0fINq47j4ShiJGD5uT7kty66La2u+yO5IbGpf9/AOzHWh6EzjAeTOaNPA=
    NOTION_TOKEN: AgAEoif1rWUZTGsppkAWVkVQ9NwblnOEfbO1uQQ8Ckr40oAh3JDZWhjzRVTCfkrCOarrdbQaTmJ1CCcLcYdFb2+KYBLMZl4Av//6NR15KHKZZ1H3I40xPOXyZx3dLwcYfi/6QQaJAPk/1xxxdQMWamV+WmqAvhZ+T4O1isZDmv7g7tHbG1jNUGyZosZwK0PR9n5ZJr61f3P0tkAVCo3zzFi1aQAlbDy/pkay9J6P9nDImRcHc8FeTKyn9D9vPqKAklRX8r1jB2bLst99RQIsNITwoHKsemmcUoWkqtYtz397UY26ScQYum9qj8KpU8Fo+mtMd/BSVPzmBnZa5YNbIPCviH5xacglICA61TW21mBICk2nfIuo3+P3zRefjDUTd1Co7i9+NQddQ8h0aajYLI7+oqt3TVHUO2xGjd1QiqjvLmYXYXLNetQt3AmrQ6jopvSO9gvMg4hDTx8mGDbkJRhA9ghDYY1k+x3i4JxAyjdA7obkgmvyvhXESIMb/IaLP61czdwCzGV40yG7tn+QitHqwqmDhYUtdStj9MxZ1idEjIe/i2uuINQ2sikITeSA4bTwh8dWTW6bFqjHpUNcS6/6nBnIY3wm5NmLcjDv+T10CWo4M8JR8SVwNrT0L8rMFtd80WnDP1q1N5BK7NJ9UYtqQVy3VciXQkR/s8ndFomBHx2egUuHfCjIw1Z+9maFEPm5mgG8acU287nhbwcx2mfDJRQSvzmmKJ6PgjxY3a3FINFdZSBn/SXiwVIJuy5lDzis9A==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: notion-to-calendar
      name: notion-to-calendar-secrets
      namespace: default
    type: Opaque
